### ISSUE TITLE
Не хочет запускаться

### ISSUE THREAD

**Issue by pabo4u** [oppan31/catizen-auto-bot#2]

**Comment by youngbloodes** [comment]
![image](https://github.com/oppan31/catizen-auto-bot/assets/136193213/8b3ced1d-0ebd-4034-ba2f-d6859dcdbf22)

**Comment by pabo4u** [comment]
> ![image](https://private-user-images.githubusercontent.com/136193213/326251670-8b3ced1d-0ebd-4034-ba2f-d6859dcdbf22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDI0MjksIm5iZiI6MTcxNDM0MjEyOSwicGF0aCI6Ii8xMzYxOTMyMTMvMzI2MjUxNjcwLThiM2NlZDFkLTBlYmQtNDAzNC1iYTJmLWQ2ODU5ZGNkYmYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMjA4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWYzM2I3NDE1NDA2OTI0MmEzOWMwOTJjMzdmODM5OWJkZDBjZGE1MDk3MDMyMmM2MDI1YmMyMGNiNDhlYTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8AB8CxqY4qXK_Ykig3SYEzzVkbZSf7E6YhggBZHXNTs)

тоже самое скорее всего вирус
